### ISSUE TITLE
Reminder: Module unfulfilled prerequisites

### ISSUE THREAD

**Issue by douglaswja** [AY2021S2-CS2103-W17-1/tp#13]
As a basic user, I would like to be reminded if I plan for modules I don’t fulfil requirements for

**Comment by ssagit** [comment]
This is for singular adding of modules (i.e. if I add 3230, I may be reminded that I have not completed CS2040), different from https://github.com/AY2021S2-CS2103-W17-1/tp/issues/17

**Comment by ssagit** [comment]
Closing as requirements changed: this feature would have taken too long to do.
