### ISSUE TITLE
Update UG

### ISSUE THREAD

**Issue by ssagit** [AY2021S2-CS2103-W17-1/tp#21]
Individual task, issue should be closed when everyone is done

**Comment by douglaswja** [comment]
done with my commands

**Comment by BenedictBCJJ** [comment]
done

**Comment by Yihe-Harry** [comment]
done, ive made the pr

**Comment by ssagit** [comment]
done w my portion

**Comment by seaniy** [comment]
done

**Comment by seaniy** [comment]
Everyone's done with individual tasks. Closing issue.
