### ISSUE TITLE
Graduation: Check if graduation requirements are met

### ISSUE THREAD

**Issue by douglaswja** [AY2021S2-CS2103-W17-1/tp#24]
As a student I can check if I have fulfilled all my graduation requirements.

Note that this would require our product to be informed of each graduation requirement of each specialization possible of every major in NUS.
We have two options:
1. Narrow down our target user base to CS SWE spec.
2. Avoid this feature entirely and reframe our product as handling module planning (i.e. preqrequisites and semester offered) only.

**Comment by ssagit** [comment]
Closing as requirements changed: this feature would have taken too long to do.
