### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by douglaswja** [AY2021S2-CS2103-W17-1/tp#37]
Haochen:
* Target user profile
* Value proposition

Douglas:
* User Stories

Yihe:
* Glossary

Sean:
* Use Cases

Ben:
* Non-functional requirements

Remember to take note of the grading rubrics for the DG as mentioned under [Point 4 of the Week 7 Project Page](https://nus-cs2103-ay2021s2.github.io/website/schedule/week7/project.html).

**Comment by douglaswja** [comment]
Done with User Stories

**Comment by ssagit** [comment]
done w my portion

**Comment by seaniy** [comment]
Done with Use Cases, added 3 use cases. Not sure if need to add more.
